# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = E:\cmake-3.29.0-windows-x86_64\bin\cmake.exe

# The command to remove a file.
RM = E:\cmake-3.29.0-windows-x86_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\user\Desktop\name\C++\yuanqi_qishi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\user\Desktop\name\C++\yuanqi_qishi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	E:\cmake-3.29.0-windows-x86_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	E:\cmake-3.29.0-windows-x86_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\user\Desktop\name\C++\yuanqi_qishi\CMakeFiles C:\Users\user\Desktop\name\C++\yuanqi_qishi\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\user\Desktop\name\C++\yuanqi_qishi\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yuanqi_qishi

# Build rule for target.
yuanqi_qishi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 yuanqi_qishi
.PHONY : yuanqi_qishi

# fast build rule for target.
yuanqi_qishi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/build
.PHONY : yuanqi_qishi/fast

#=============================================================================
# Target rules for targets named copy_audio_plugins

# Build rule for target.
copy_audio_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 copy_audio_plugins
.PHONY : copy_audio_plugins

# fast build rule for target.
copy_audio_plugins/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\copy_audio_plugins.dir\build.make CMakeFiles/copy_audio_plugins.dir/build
.PHONY : copy_audio_plugins/fast

#=============================================================================
# Target rules for targets named yuanqi_qishi_autogen_timestamp_deps

# Build rule for target.
yuanqi_qishi_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 yuanqi_qishi_autogen_timestamp_deps
.PHONY : yuanqi_qishi_autogen_timestamp_deps

# fast build rule for target.
yuanqi_qishi_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi_autogen_timestamp_deps.dir\build.make CMakeFiles/yuanqi_qishi_autogen_timestamp_deps.dir/build
.PHONY : yuanqi_qishi_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named yuanqi_qishi_autogen

# Build rule for target.
yuanqi_qishi_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 yuanqi_qishi_autogen
.PHONY : yuanqi_qishi_autogen

# fast build rule for target.
yuanqi_qishi_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi_autogen.dir\build.make CMakeFiles/yuanqi_qishi_autogen.dir/build
.PHONY : yuanqi_qishi_autogen/fast

src/app/app.obj: src/app/app.cpp.obj
.PHONY : src/app/app.obj

# target to build an object file
src/app/app.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/app/app.cpp.obj
.PHONY : src/app/app.cpp.obj

src/app/app.i: src/app/app.cpp.i
.PHONY : src/app/app.i

# target to preprocess a source file
src/app/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/app/app.cpp.i
.PHONY : src/app/app.cpp.i

src/app/app.s: src/app/app.cpp.s
.PHONY : src/app/app.s

# target to generate assembly for a file
src/app/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/app/app.cpp.s
.PHONY : src/app/app.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/model.obj: src/model/model.cpp.obj
.PHONY : src/model/model.obj

# target to build an object file
src/model/model.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/model/model.cpp.obj
.PHONY : src/model/model.cpp.obj

src/model/model.i: src/model/model.cpp.i
.PHONY : src/model/model.i

# target to preprocess a source file
src/model/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/model/model.cpp.i
.PHONY : src/model/model.cpp.i

src/model/model.s: src/model/model.cpp.s
.PHONY : src/model/model.s

# target to generate assembly for a file
src/model/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/model/model.cpp.s
.PHONY : src/model/model.cpp.s

src/view/mainwindow.obj: src/view/mainwindow.cpp.obj
.PHONY : src/view/mainwindow.obj

# target to build an object file
src/view/mainwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/view/mainwindow.cpp.obj
.PHONY : src/view/mainwindow.cpp.obj

src/view/mainwindow.i: src/view/mainwindow.cpp.i
.PHONY : src/view/mainwindow.i

# target to preprocess a source file
src/view/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/view/mainwindow.cpp.i
.PHONY : src/view/mainwindow.cpp.i

src/view/mainwindow.s: src/view/mainwindow.cpp.s
.PHONY : src/view/mainwindow.s

# target to generate assembly for a file
src/view/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/view/mainwindow.cpp.s
.PHONY : src/view/mainwindow.cpp.s

src/view/sink/mainwindowsink.obj: src/view/sink/mainwindowsink.cpp.obj
.PHONY : src/view/sink/mainwindowsink.obj

# target to build an object file
src/view/sink/mainwindowsink.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/view/sink/mainwindowsink.cpp.obj
.PHONY : src/view/sink/mainwindowsink.cpp.obj

src/view/sink/mainwindowsink.i: src/view/sink/mainwindowsink.cpp.i
.PHONY : src/view/sink/mainwindowsink.i

# target to preprocess a source file
src/view/sink/mainwindowsink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/view/sink/mainwindowsink.cpp.i
.PHONY : src/view/sink/mainwindowsink.cpp.i

src/view/sink/mainwindowsink.s: src/view/sink/mainwindowsink.cpp.s
.PHONY : src/view/sink/mainwindowsink.s

# target to generate assembly for a file
src/view/sink/mainwindowsink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/view/sink/mainwindowsink.cpp.s
.PHONY : src/view/sink/mainwindowsink.cpp.s

src/viewmodel/commands/move.obj: src/viewmodel/commands/move.cpp.obj
.PHONY : src/viewmodel/commands/move.obj

# target to build an object file
src/viewmodel/commands/move.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/commands/move.cpp.obj
.PHONY : src/viewmodel/commands/move.cpp.obj

src/viewmodel/commands/move.i: src/viewmodel/commands/move.cpp.i
.PHONY : src/viewmodel/commands/move.i

# target to preprocess a source file
src/viewmodel/commands/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/commands/move.cpp.i
.PHONY : src/viewmodel/commands/move.cpp.i

src/viewmodel/commands/move.s: src/viewmodel/commands/move.cpp.s
.PHONY : src/viewmodel/commands/move.s

# target to generate assembly for a file
src/viewmodel/commands/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/commands/move.cpp.s
.PHONY : src/viewmodel/commands/move.cpp.s

src/viewmodel/sink/viewmodelsink.obj: src/viewmodel/sink/viewmodelsink.cpp.obj
.PHONY : src/viewmodel/sink/viewmodelsink.obj

# target to build an object file
src/viewmodel/sink/viewmodelsink.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/sink/viewmodelsink.cpp.obj
.PHONY : src/viewmodel/sink/viewmodelsink.cpp.obj

src/viewmodel/sink/viewmodelsink.i: src/viewmodel/sink/viewmodelsink.cpp.i
.PHONY : src/viewmodel/sink/viewmodelsink.i

# target to preprocess a source file
src/viewmodel/sink/viewmodelsink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/sink/viewmodelsink.cpp.i
.PHONY : src/viewmodel/sink/viewmodelsink.cpp.i

src/viewmodel/sink/viewmodelsink.s: src/viewmodel/sink/viewmodelsink.cpp.s
.PHONY : src/viewmodel/sink/viewmodelsink.s

# target to generate assembly for a file
src/viewmodel/sink/viewmodelsink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/sink/viewmodelsink.cpp.s
.PHONY : src/viewmodel/sink/viewmodelsink.cpp.s

src/viewmodel/viewmodel.obj: src/viewmodel/viewmodel.cpp.obj
.PHONY : src/viewmodel/viewmodel.obj

# target to build an object file
src/viewmodel/viewmodel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/viewmodel.cpp.obj
.PHONY : src/viewmodel/viewmodel.cpp.obj

src/viewmodel/viewmodel.i: src/viewmodel/viewmodel.cpp.i
.PHONY : src/viewmodel/viewmodel.i

# target to preprocess a source file
src/viewmodel/viewmodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/viewmodel.cpp.i
.PHONY : src/viewmodel/viewmodel.cpp.i

src/viewmodel/viewmodel.s: src/viewmodel/viewmodel.cpp.s
.PHONY : src/viewmodel/viewmodel.s

# target to generate assembly for a file
src/viewmodel/viewmodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/src/viewmodel/viewmodel.cpp.s
.PHONY : src/viewmodel/viewmodel.cpp.s

yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.obj: yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.obj
.PHONY : yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.obj

# target to build an object file
yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.obj
.PHONY : yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.obj

yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.i: yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.i
.PHONY : yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.i

# target to preprocess a source file
yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.i
.PHONY : yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.i

yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.s: yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.s
.PHONY : yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.s

# target to generate assembly for a file
yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.s
.PHONY : yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.cpp.s

yuanqi_qishi_autogen/mocs_compilation.obj: yuanqi_qishi_autogen/mocs_compilation.cpp.obj
.PHONY : yuanqi_qishi_autogen/mocs_compilation.obj

# target to build an object file
yuanqi_qishi_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/yuanqi_qishi_autogen/mocs_compilation.cpp.obj
.PHONY : yuanqi_qishi_autogen/mocs_compilation.cpp.obj

yuanqi_qishi_autogen/mocs_compilation.i: yuanqi_qishi_autogen/mocs_compilation.cpp.i
.PHONY : yuanqi_qishi_autogen/mocs_compilation.i

# target to preprocess a source file
yuanqi_qishi_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/yuanqi_qishi_autogen/mocs_compilation.cpp.i
.PHONY : yuanqi_qishi_autogen/mocs_compilation.cpp.i

yuanqi_qishi_autogen/mocs_compilation.s: yuanqi_qishi_autogen/mocs_compilation.cpp.s
.PHONY : yuanqi_qishi_autogen/mocs_compilation.s

# target to generate assembly for a file
yuanqi_qishi_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\yuanqi_qishi.dir\build.make CMakeFiles/yuanqi_qishi.dir/yuanqi_qishi_autogen/mocs_compilation.cpp.s
.PHONY : yuanqi_qishi_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... copy_audio_plugins
	@echo ... yuanqi_qishi_autogen
	@echo ... yuanqi_qishi_autogen_timestamp_deps
	@echo ... yuanqi_qishi
	@echo ... src/app/app.obj
	@echo ... src/app/app.i
	@echo ... src/app/app.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/model/model.obj
	@echo ... src/model/model.i
	@echo ... src/model/model.s
	@echo ... src/view/mainwindow.obj
	@echo ... src/view/mainwindow.i
	@echo ... src/view/mainwindow.s
	@echo ... src/view/sink/mainwindowsink.obj
	@echo ... src/view/sink/mainwindowsink.i
	@echo ... src/view/sink/mainwindowsink.s
	@echo ... src/viewmodel/commands/move.obj
	@echo ... src/viewmodel/commands/move.i
	@echo ... src/viewmodel/commands/move.s
	@echo ... src/viewmodel/sink/viewmodelsink.obj
	@echo ... src/viewmodel/sink/viewmodelsink.i
	@echo ... src/viewmodel/sink/viewmodelsink.s
	@echo ... src/viewmodel/viewmodel.obj
	@echo ... src/viewmodel/viewmodel.i
	@echo ... src/viewmodel/viewmodel.s
	@echo ... yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.obj
	@echo ... yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.i
	@echo ... yuanqi_qishi_autogen/UVLADIE3JM/qrc_images.s
	@echo ... yuanqi_qishi_autogen/mocs_compilation.obj
	@echo ... yuanqi_qishi_autogen/mocs_compilation.i
	@echo ... yuanqi_qishi_autogen/mocs_compilation.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

